[book]
authors = ["pineapple"]
language = "en"
multilingual = false
src = "src"
title = "🍍"
description="Pineapple Proxy - spiderweb of the new internet"

[output.html]
git-repository-url = "https://github.com/Pineapple-Proxy-DAO/web"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Pineapple-Proxy-DAO/web/edit/main/{path}"
default-theme = "light"
preferred-dark-theme = "navy"
site-url = "/web/"
